# Site settings
title: Общество 
email: ""
description: "Дорогие 
"
baseurl: ""
url: "http://rufolketnashestvie.herokuapp.com"
titlelogo: '/img/title-logo.png'
paginate: 5
defaults:
 - scope:
      path: "" # an empty string here means all files in the project
   values:
      layout: page

# Build settings
markdown: kramdown
timezone: Europe/Moscow

# Server settings
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'ЧИНИ']

# plugins
plugins: [jekyll-paginate]
